// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
// import Navbar from '@/components/Navbar'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Sean Alden',
//   description: 'IT Professional Portfolio',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="id">
//       <body className={`${inter.className} bg-gray-50 text-gray-900 min-h-screen flex flex-col`}>
//         <Navbar />
//         <main className="flex-grow max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 w-full">
//           {children}
//         </main>
//         <footer className="text-center py-6 text-sm text-gray-500 border-t">
//           © {new Date().getFullYear()} NAMA SAYA. All rights reserved.
//         </footer>
//       </body>
//     </html>
//   )
// }

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
// Import ikon yang dijamin aman dari error
import { Link as LinkIcon, GitBranch, Camera, MessageCircle } from 'lucide-react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Sean Alden | Portfolio',
  description: 'IT Professional Portfolio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    // Tambahkan scroll-smooth di tag html untuk mendukung navigasi anchor link
    <html lang="id" className="scroll-smooth">
      <body className={`${inter.className} bg-gray-50 text-gray-900 min-h-screen flex flex-col`}>
        <Navbar />
        
        <main className="flex-grow max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 w-full">
          {children}
        </main>
        
        {/* FOOTER BARU DENGAN SOSIAL MEDIA */}
        <footer className="w-full bg-white border-t border-gray-200 mt-auto">
          <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
            <div className="flex flex-col md:flex-row justify-between items-center gap-4">
              
              {/* Copyright */}
              <div className="text-sm text-gray-500 font-medium">
                © {new Date().getFullYear()} Sean Alden. All rights reserved.
              </div>

              {/* Social Links */}
              <div className="flex items-center space-x-6">
                <a 
                  href="https://github.com/SeanAlden" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-gray-900 hover:-translate-y-1 transition-all duration-300"
                  title="GitHub"
                >
                  <GitBranch className="w-5 h-5" />
                </a>
                
                <a 
                  href="https://linkedin.com/in/sean-alden" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-blue-700 hover:-translate-y-1 transition-all duration-300"
                  title="LinkedIn"
                >
                  <LinkIcon className="w-5 h-5" />
                </a>
                
                <a 
                  href="https://instagram.com/username_ig_anda" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-pink-600 hover:-translate-y-1 transition-all duration-300"
                  title="Instagram"
                >
                  <Camera className="w-5 h-5" />
                </a>
                
                <a 
                  href="https://wa.me/6281234567890" 
                  target="_blank" 
                  rel="noopener noreferrer"
                  className="text-gray-400 hover:text-green-500 hover:-translate-y-1 transition-all duration-300"
                  title="WhatsApp"
                >
                  <MessageCircle className="w-5 h-5" />
                </a>
              </div>

            </div>
          </div>
        </footer>
      </body>
    </html>
  )
}