// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

// import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
// import './globals.css'
// import Navbar from '@/components/Navbar'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Sean Alden',
//   description: 'IT Professional Portfolio',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="id">
//       <body className={`${inter.className} bg-gray-50 text-gray-900 min-h-screen flex flex-col`}>
//         <Navbar />
//         <main className="flex-grow max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 w-full">
//           {children}
//         </main>
//         <footer className="text-center py-6 text-sm text-gray-500 border-t">
//           © {new Date().getFullYear()} NAMA SAYA. All rights reserved.
//         </footer>
//       </body>
//     </html>
//   )
// }

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import Navbar from '@/components/Navbar'
import Image from 'next/image'
import { personalInfo } from '@/data/portfolio' // Mengambil data dinamis

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: personalInfo.name,
  description: 'IT Professional Portfolio',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="id" className="scroll-smooth">
      <body className={`${inter.className} bg-gray-50 text-gray-900 min-h-screen flex flex-col`}>
        <Navbar />
        
        <main className="flex-grow max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-12 w-full">
          {children}
        </main>
        
        <footer className="w-full bg-white border-t py-8 mt-auto">
          <div className="max-w-5xl mx-auto px-4 flex flex-col items-center space-y-5">
            
            {/* Social Media Icons */}
            <div className="flex items-center space-x-6">
              
              {/* GitHub - Diambil dari portfolio.ts */}
              <a href={`https://${personalInfo.github}`} target="_blank" rel="noopener noreferrer" className="hover:-translate-y-1 hover:opacity-80 transition-all duration-300">
                <Image src="/icons/github.png" alt="GitHub" width={28} height={28} className="object-contain" />
              </a>
              
              {/* LinkedIn - Diambil dari portfolio.ts */}
              <a href={`https://${personalInfo.linkedin}`} target="_blank" rel="noopener noreferrer" className="hover:-translate-y-1 hover:opacity-80 transition-all duration-300">
                <Image src="/icons/linkedin.png" alt="LinkedIn" width={28} height={28} className="object-contain" />
              </a>
              
              {/* Instagram - Silakan ubah 'username_anda' */}
              <a href="https://instagram.com/username_anda" target="_blank" rel="noopener noreferrer" className="hover:-translate-y-1 hover:opacity-80 transition-all duration-300">
                <Image src="/icons/instagram.png" alt="Instagram" width={28} height={28} className="object-contain" />
              </a>
              
              {/* WhatsApp - Silakan ubah format nomor menjadi 628... tanpa spasi atau plus */}
              <a href="https://wa.me/6281234567890" target="_blank" rel="noopener noreferrer" className="hover:-translate-y-1 hover:opacity-80 transition-all duration-300">
                <Image src="/icons/whatsapp.png" alt="WhatsApp" width={28} height={28} className="object-contain" />
              </a>
              
            </div>
            
            {/* Copyright Text */}
            <p className="text-center text-sm text-gray-500 font-medium">
              © {new Date().getFullYear()} {personalInfo.name}. All rights reserved.
            </p>
          </div>
        </footer>

      </body>
    </html>
  )
}